name: learnify
services:
  learnify:
    image: ghcr.io/a1exsun/learnify-graphql:canary
    container_name: learnify_server
    network_mode: host
    environment:
      - REDIS_SERVER_HOST=intent-dane-12047.upstash.io
      - REDIS_SERVER_PORT=6379
      - REDIS_SERVER_USERNAME=default
      - REDIS_SERVER_PASSWORD=AS8PAAIjcDE4NmU0MWVjZjMwODg0OGU4OTYwNDVhNzU2MjE5NjhjYnAxMA
      - REDIS_SERVER_TLS=true 
      - REDIS_SERVER_DATABASE=0
      - DATABASE_URL=postgresql://postgres:gipjen-wesny1-gutXog@db.kbruxxqmqzduwsylxgdv.supabase.co:5432/postgres
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped
