{{- if .Values.global.indexer.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: indexer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  indexer-apiKey: {{ .Values.global.indexer.apiKey | b64enc }}
{{- end }}
