export const mockPodcastItems = [
  // AI & Machine Learning
  {
    id: 'podcast-001',
    title: 'Deep Learning Fundamentals',
    description: 'Understanding neural networks from scratch',
    duration: '45:30',
    category: 'AI Tech',
    date: '2024-01-15',
    hosts: ['Dr. Sarah Chen', 'Mike Johnson'],
  },
  {
    id: 'podcast-002',
    title: 'GPT Architecture Explained',
    description: 'How transformer models revolutionized NLP',
    duration: '52:15',
    category: 'AI Tech',
    date: '2024-01-14',
  },
  {
    id: 'podcast-003',
    title: 'Computer Vision in Production',
    description: 'Real-world applications of image recognition',
    duration: '41:20',
    category: 'AI Tech',
    date: '2024-01-13',
  },
  {
    id: 'podcast-004',
    title: 'Reinforcement Learning Basics',
    description: 'Teaching machines to learn through rewards',
    duration: '38:45',
    category: 'AI Tech',
    date: '2024-01-12',
  },
  {
    id: 'podcast-005',
    title: 'AI Ethics and Bias',
    description: 'Addressing fairness in machine learning models',
    duration: '47:30',
    category: 'AI Tech',
    date: '2024-01-11',
  },
  {
    id: 'podcast-006',
    title: 'Natural Language Processing',
    description: 'Building chatbots and language models',
    duration: '44:10',
    category: 'AI Tech',
    date: '2024-01-10',
  },

  // Frontend Development
  {
    id: 'podcast-007',
    title: 'React 18 New Features',
    description: 'Exploring Concurrent Mode and Suspense',
    duration: '38:45',
    category: 'Frontend Dev',
    date: '2024-01-09',
  },
  {
    id: 'podcast-008',
    title: 'Next.js App Router Deep Dive',
    description: 'Server components and streaming SSR',
    duration: '42:20',
    category: 'Frontend Dev',
    date: '2024-01-08',
  },
  {
    id: 'podcast-009',
    title: 'Vue 3 Composition API',
    description: 'Modern Vue development patterns',
    duration: '36:15',
    category: 'Frontend Dev',
    date: '2024-01-07',
  },
  {
    id: 'podcast-010',
    title: 'State Management in 2024',
    description: 'Comparing Redux, Zustand, and Jotai',
    duration: '40:30',
    category: 'Frontend Dev',
    date: '2024-01-06',
  },
  {
    id: 'podcast-011',
    title: 'CSS Modern Layouts',
    description: 'Grid, Flexbox, and Container Queries',
    duration: '33:45',
    category: 'Frontend Dev',
    date: '2024-01-05',
  },
  {
    id: 'podcast-012',
    title: 'Web Performance Optimization',
    description: 'Core Web Vitals and loading strategies',
    duration: '45:20',
    category: 'Frontend Dev',
    date: '2024-01-04',
  },
  {
    id: 'podcast-013',
    title: 'Micro Frontends Architecture',
    description: 'Building scalable frontend applications',
    duration: '48:10',
    category: 'Frontend Dev',
    date: '2024-01-03',
  },

  // Product Design
  {
    id: 'podcast-014',
    title: 'Design Systems at Scale',
    description: 'Building consistent UI across teams',
    duration: '39:45',
    category: 'Product Design',
    date: '2024-01-02',
  },
  {
    id: 'podcast-015',
    title: 'User Research Methods',
    description: 'Gathering insights for better products',
    duration: '43:30',
    category: 'Product Design',
    date: '2024-01-01',
  },
  {
    id: 'podcast-016',
    title: 'Product-Market Fit',
    description: 'Finding and validating your target audience',
    duration: '51:20',
    category: 'Product Design',
    date: '2023-12-31',
  },
  {
    id: 'podcast-017',
    title: 'A/B Testing Strategies',
    description: 'Data-driven product decision making',
    duration: '37:15',
    category: 'Product Design',
    date: '2023-12-30',
  },
  {
    id: 'podcast-018',
    title: 'Mobile-First Design',
    description: 'Creating seamless mobile experiences',
    duration: '35:40',
    category: 'Product Design',
    date: '2023-12-29',
  },
  {
    id: 'podcast-019',
    title: 'Accessibility Best Practices',
    description: 'Building inclusive digital products',
    duration: '42:25',
    category: 'Product Design',
    date: '2023-12-28',
  },

  // Architecture
  {
    id: 'podcast-020',
    title: 'Microservices Architecture',
    description: 'Breaking down monolithic applications',
    duration: '46:30',
    category: 'Architecture',
    date: '2023-12-27',
  },
  {
    id: 'podcast-021',
    title: 'Event-Driven Architecture',
    description: 'Building reactive systems with message queues',
    duration: '44:15',
    category: 'Architecture',
    date: '2023-12-26',
  },
  {
    id: 'podcast-022',
    title: 'Domain-Driven Design',
    description: 'Modeling complex business domains',
    duration: '49:20',
    category: 'Architecture',
    date: '2023-12-25',
  },
  {
    id: 'podcast-023',
    title: 'Database Scaling Strategies',
    description: 'Sharding, replication, and caching',
    duration: '41:45',
    category: 'Architecture',
    date: '2023-12-24',
  },
  {
    id: 'podcast-024',
    title: 'API Gateway Patterns',
    description: 'Managing microservices communication',
    duration: '38:30',
    category: 'Architecture',
    date: '2023-12-23',
  },
  {
    id: 'podcast-025',
    title: 'Cloud-Native Architecture',
    description: 'Building for AWS, Azure, and GCP',
    duration: '47:10',
    category: 'Architecture',
    date: '2023-12-22',
  },

  // Programming Languages
  {
    id: 'podcast-026',
    title: 'TypeScript Advanced Types',
    description: 'Type gymnastics and practical applications',
    duration: '35:40',
    category: 'Languages',
    date: '2023-12-21',
  },
  {
    id: 'podcast-027',
    title: 'Rust for Web Development',
    description: 'Building high-performance web services',
    duration: '43:25',
    category: 'Languages',
    date: '2023-12-20',
  },
  {
    id: 'podcast-028',
    title: 'Go Concurrency Patterns',
    description: 'Goroutines and channels explained',
    duration: '40:15',
    category: 'Languages',
    date: '2023-12-19',
  },
  {
    id: 'podcast-029',
    title: 'Python Async Programming',
    description: 'Understanding asyncio and coroutines',
    duration: '37:50',
    category: 'Languages',
    date: '2023-12-18',
  },
  {
    id: 'podcast-030',
    title: 'Java Virtual Threads',
    description: 'Project Loom and the future of Java',
    duration: '45:30',
    category: 'Languages',
    date: '2023-12-17',
  },
  {
    id: 'podcast-031',
    title: 'Swift UI Development',
    description: 'Building modern iOS applications',
    duration: '42:20',
    category: 'Languages',
    date: '2023-12-16',
  },

  // Startup & Business
  {
    id: 'podcast-032',
    title: 'Tech Stack for Startups',
    description: 'Choosing the right tools with limited resources',
    duration: '48:30',
    category: 'Startup',
    date: '2023-12-15',
  },
  {
    id: 'podcast-033',
    title: 'Scaling from 0 to 1M Users',
    description: 'Infrastructure evolution at different stages',
    duration: '52:45',
    category: 'Startup',
    date: '2023-12-14',
  },
  {
    id: 'podcast-034',
    title: 'Building Remote Teams',
    description: 'Culture and processes for distributed work',
    duration: '44:20',
    category: 'Startup',
    date: '2023-12-13',
  },
  {
    id: 'podcast-035',
    title: 'Fundraising for Tech Startups',
    description: 'From seed to Series A and beyond',
    duration: '50:15',
    category: 'Startup',
    date: '2023-12-12',
  },
  {
    id: 'podcast-036',
    title: 'MVP Development Strategy',
    description: 'Building products that users actually want',
    duration: '39:40',
    category: 'Startup',
    date: '2023-12-11',
  },

  // DevOps
  {
    id: 'podcast-037',
    title: 'Kubernetes Best Practices',
    description: 'Container orchestration in production',
    duration: '43:25',
    category: 'DevOps',
    date: '2023-12-10',
  },
  {
    id: 'podcast-038',
    title: 'CI/CD Pipeline Automation',
    description: 'GitHub Actions, Jenkins, and GitLab CI',
    duration: '41:30',
    category: 'DevOps',
    date: '2023-12-09',
  },
  {
    id: 'podcast-039',
    title: 'Infrastructure as Code',
    description: 'Terraform and CloudFormation patterns',
    duration: '46:20',
    category: 'DevOps',
    date: '2023-12-08',
  },
  {
    id: 'podcast-040',
    title: 'Monitoring and Observability',
    description: 'Prometheus, Grafana, and distributed tracing',
    duration: '44:15',
    category: 'DevOps',
    date: '2023-12-07',
  },
  {
    id: 'podcast-041',
    title: 'Docker Optimization Tips',
    description: 'Building smaller and faster containers',
    duration: '36:45',
    category: 'DevOps',
    date: '2023-12-06',
  },
  {
    id: 'podcast-042',
    title: 'GitOps Workflows',
    description: 'Flux, ArgoCD, and declarative deployments',
    duration: '42:30',
    category: 'DevOps',
    date: '2023-12-05',
  },

  // Career Development
  {
    id: 'podcast-043',
    title: 'Technical Interview Prep',
    description: 'System design and coding challenges',
    duration: '39:50',
    category: 'Career',
    date: '2023-12-04',
  },
  {
    id: 'podcast-044',
    title: 'From Engineer to Manager',
    description: 'Transitioning to engineering leadership',
    duration: '47:20',
    category: 'Career',
    date: '2023-12-03',
  },
  {
    id: 'podcast-045',
    title: 'Building Your Tech Portfolio',
    description: 'Projects that impress recruiters',
    duration: '35:15',
    category: 'Career',
    date: '2023-12-02',
  },
  {
    id: 'podcast-046',
    title: 'Salary Negotiation Tips',
    description: 'Getting the compensation you deserve',
    duration: '41:40',
    category: 'Career',
    date: '2023-12-01',
  },
  {
    id: 'podcast-047',
    title: 'Remote Work Best Practices',
    description: 'Staying productive and connected',
    duration: '38:25',
    category: 'Career',
    date: '2023-11-30',
  },
  {
    id: 'podcast-048',
    title: 'Open Source Contributions',
    description: 'Building reputation through OSS',
    duration: '43:30',
    category: 'Career',
    date: '2023-11-29',
  },
  {
    id: 'podcast-049',
    title: 'Tech Conference Speaking',
    description: 'Sharing knowledge and building network',
    duration: '40:15',
    category: 'Career',
    date: '2023-11-28',
  },
  {
    id: 'podcast-050',
    title: 'Work-Life Balance in Tech',
    description: 'Avoiding burnout and staying healthy',
    duration: '45:50',
    category: 'Career',
    date: '2023-11-27',
  },
];

// Add random hosts to all items
const hostNames = [
  'Dr. Sarah Chen',
  'Mike Johnson',
  'Emily Rodriguez',
  'Alex Thompson',
  'Jessica Liu',
  'David Park',
  'Rachel Green',
  'Tom Wilson',
  'Lisa Anderson',
  'Chris Martinez',
  'Anna Schmidt',
  'Kevin Lee',
];

// Add hosts to each podcast item if not already present
mockPodcastItems.forEach(item => {
  if (!item.hosts) {
    const numHosts = Math.floor(Math.random() * 3) + 1; // 1-3 hosts
    const shuffled = [...hostNames].sort(() => 0.5 - Math.random());
    item.hosts = shuffled.slice(0, numHosts);
  }
});

export const mockPodcastsData = [
  {
    key: 'all',
    items: mockPodcastItems.map(item => item.id),
  },
];
