export const mockSources = [
  {
    id: '1',
    name: 'mat9004_lecture03',
    category: 'pdf',
    description: 'The third lecture slides for MAT9004',
  },
  {
    id: '2',
    name: 'mat9004_lecture04',
    category: 'pdf',
    description: 'The fourth lecture slides for MAT9004',
  },
  {
    id: '3',
    name: 'mat9004_lecture03_handwritten',
    category: 'image',
    description: 'The handwritten notes for the third lecture',
  },
  {
    id: '4',
    name: 'mat9004_lecture04_handwritten',
    category: 'image',
    description: 'The handwritten notes for the fourth lecture',
  },
  {
    id: '5',
    name: 'mat9004_lecture05',
    category: 'pdf',
    description: 'The fifth lecture slides for MAT9004',
  },
  {
    id: '6',
    name: 'mat9004_lecture06',
    category: 'pdf',
    description: 'The sixth lecture slides for MAT9004',
  },
  {
    id: '7',
    name: 'scan_gmarkow_2025-03-25-12-52-26',
    category: 'image',
    description: 'The handwritten notes for the sixth lecture',
  },
  {
    id: '8',
    name: 'MAT9004 Handbook',
    url: 'https://handbook.monash.edu/2025/units/MAT9004',
    category: 'link',
    description: 'The handbook for MAT9004',
  },
  {
    id: '10',
    name: 'mat9004_lecture03',
    category: 'pdf',
    description: 'The third lecture slides for MAT9004',
  },
  {
    id: '11',
    name: 'mat9004_lecture04',
    category: 'pdf',
    description: 'The fourth lecture slides for MAT9004',
  },
  {
    id: '12',
    name: 'mat9004_lecture03_handwritten',
    category: 'image',
    description: 'The handwritten notes for the third lecture',
  },
  {
    id: '13',
    name: 'mat9004_lecture04_handwritten',
    category: 'image',
    description: 'The handwritten notes for the fourth lecture',
  },
  {
    id: '14',
    name: 'mat9004_lecture05',
    category: 'pdf',
    description: 'The fifth lecture slides for MAT9004',
  },
  {
    id: '15',
    name: 'mat9004_lecture06',
    category: 'pdf',
    description: 'The sixth lecture slides for MAT9004',
  },
  {
    id: '16',
    name: 'scan_gmarkow_2025-03-25-12-52-26',
    category: 'image',
    description: 'The handwritten notes for the sixth lecture',
  },
  {
    id: '17',
    name: 'MAT9004 Handbook',
    url: 'https://handbook.monash.edu/2025/units/MAT9004',
    category: 'link',
    description: 'The handbook for MAT9004',
  },
];
