name: Feature Request
description: Suggest a feature or improvement
title: '[Feature Request]: '
labels: ['feat', 'story']
assignees: ['alexsun']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature suggestion!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added to Learnify?
      placeholder: Please explain in details the feature and improvements you'd like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        How might this feature be used and who might use it.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the idea you have!
        Tip: You can attach images here
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      options:
        - label: Yes I'd like to help by submitting a PR!
