name: learnify
services:
  learnify:
    image: ghcr.io/a1exsun/learnify
    container_name: learnify
    ports:
      - '${PORT:-80}:3010'
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=${REDIS_HOST}
      - REDIS_SERVER_PORT=${REDIS_PORT}
      - REDIS_SERVER_USERNAME=${REDIS_USERNAME}
      - REDIS_SERVER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SERVER_DATABASE=${REDIS_DATABASE}
      - REDIS_SERVER_TLS=${REDIS_TLS}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_DATABASE}
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped