name: Build Images by Branch Update

on:
  push:
    branches:
      - canary
      - dev

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-images.yml
    with:
      flavor: ${{ github.ref_name == 'dev' && 'beta' || 'canary' }}

  sync-to-gcp:
    name: Sync Images to GCP Artifact Registry
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Set up environment variables
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "RELEASE_FLAVOR=beta" >> "$GITHUB_ENV"
          else
            echo "RELEASE_FLAVOR=canary" >> "$GITHUB_ENV"
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Pull and retag GraphQL image
        run: |
          # Pull the image from GHCR
          docker pull ghcr.io/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }}

          # Tag for GCP Artifact Registry
          docker tag ghcr.io/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }} \
            us-central1-docker.pkg.dev/learnify-463605/ghcr-proxy/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }}

      - name: Push to GCP Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/learnify-463605/ghcr-proxy/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }}

      - name: Cleanup local images
        run: |
          docker rmi ghcr.io/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }} || true
          docker rmi us-central1-docker.pkg.dev/learnify-463605/ghcr-proxy/a1exsun/learnify-graphql:${{ env.RELEASE_FLAVOR }} || true
