name: Build Images Manually

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select distribution to build'
        type: choice
        default: canary
        options:
          - canary
          - dev

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-images.yml
    with:
      flavor: ${{ github.event.inputs.flavor }}
