name: Build Images Manually

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Select distribution to build'
        type: choice
        default: canary
        options:
          - canary
          - beta

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-images.yml
    with:
      build-type: ${{ github.event.inputs.build-type }}
      app-version: 0.0.0-${{ github.event.inputs.build-type }}.${{ github.run_number }}
      git-short-hash: ${{ github.sha }}
