name: Build Images by Branch Update

on:
  push:
    branches:
      - canary
      - dev

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-images.yml
    with:
      build-type: ${{ github.ref_name == 'dev' && 'beta' || 'canary' }}
      app-version: 0.0.0-${{ github.ref_name == 'dev' && 'beta' || 'canary' }}.${{ github.run_number }}
      git-short-hash: ${{ github.sha }}

  deploy-to-tencent-cloud:
    name: Deploy to Tencent Cloud
    needs: build-image
    uses: ./.github/workflows/deploy-to-tencent-cloud.yml
    with:
      flavor: ${{ github.ref_name == 'dev' && 'beta' || 'canary' }}
    secrets: inherit
#  deploy-to-cloud-run:
#    name: Deploy to Cloud Run
#    needs: build-image
#    uses: ./.github/workflows/deploy-to-cloud-run.yml
#    with:
#      flavor: ${{ github.ref_name == 'dev' && 'beta' || 'canary' }}
#    secrets: inherit

# deploy-to-cloudflare:
#   name: Deploy to Cloudflare Containers
#   needs: build-image
#   uses: ./.github/workflows/deploy-to-cloudflare.yml
#   with:
#     flavor: ${{ github.ref_name == 'dev' && 'beta' || 'canary' }}
#   secrets: inherit
