name: Deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
        description: 'The flavor to deploy (canary, beta, stable)'
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        required: true
        description: 'The flavor to deploy'
        options:
          - canary
          - beta
          - stable

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'read'

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "RELEASE_FLAVOR=${{ inputs.flavor }}" >> "$GITHUB_ENV"
          echo "CLOUDFLARE_PROJECT_NAME=learnify" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: ./dist

      - name: Create _redirects file
        run: |
          cat > ./dist/_redirects << 'EOF'
          # Cloudflare Pages redirect rules
          # Proxy API requests to backend server
          /api/* https://server1.oiy.ai/api/:splat 200
          /graphql/* https://server1.oiy.ai/graphql/:splat 200
          /socket.io/* https://server1.oiy.ai/socket.io/:splat 200
          EOF

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.flavor }}
          wranglerVersion: '3'
